### ISSUE TITLE
Status of working players

### ISSUE THREAD

**Issue by jbpratt** [MemeLabs/url-extract#1]
|url|status|
|--|--|
|https://www.jwplayer.com/html5-video-player/ | werks|
|https://videojs.com/ | werks|
|http://player.kaltura.com/docs/ | werks|
|https://github.com/flowplayer/flowplayer | werks|
|https://wistia.com/video-marketing/player | werks|
|https://plyr.io/ | werks|
|http://jplayer.org/latest/demo-01-video/ | fails|
|http://www.mediaelementjs.com/ | fails|
|https://afterglowplayer.com/ | werks|
|https://vimeo.com/39213338 | werks|
|http://videosws.praegnanz.de/ableplayer/ | werks|
|http://videosws.praegnanz.de/bitmovin/ | werks|
|http://videosws.praegnanz.de/fluid-player/ | werks|
|http://videosws.praegnanz.de/jvideoplayer/ | werks|
|http://videosws.praegnanz.de/leanback/ | werks|
|http://videosws.praegnanz.de/ozplayer/ | werks|
|http://videosws.praegnanz.de/radiantmediaplayer/ | werks|
|http://videosws.praegnanz.de/viblast/ | werks|

Most of the HTML5 players worked without issue.

**Comment by xDashh** [comment]
Thanks for submitting the list. 
http://www.mediaelementjs.com/ seems to work with heuristics enabled, which is great to see that the effort was worth it.

http://jplayer.org/latest/demo-01-video/ is also loading a media file with heuristics on, although we don't catch the `.webm` file per default atm (not a problem though).

**Comment by xDashh** [comment]
If you find any more sites/players that don't seem to work (or only work with heuristics enabled), feel free to update/reopen here :+1:
